// Trilingual content dictionary for Pilegaard
window.PILEGAARD_I18N = {
    en: {
        nav_homes: "Summer homes", nav_lifts: "Cranes & lifts", nav_about: "The family", nav_contact: "Contact", nav_map: "Find us",
        hero_eyebrow: "A small family business · Since 1987",
        hero_title_a: "Two summer homes\nby the Danish sea.",
        hero_sub_a: "Run by the Pilegaard family from a small farm in western Jutland. Book a cabin directly, or hire a crane when you need one.",
        hero_cta_primary: "See the homes", hero_cta_secondary: "Cranes & lifts",
        homes_section_eyebrow: "Summer homes",
        homes_section_title: "Two cabins,\nchosen carefully.",
        homes_section_body: "We rent out our own two houses — no agency, no commission. One faces the dunes, one sits tucked into pine woods. Both sleep six.",
        home_1_name: "Havblik", home_1_meta: "Sleeps 6 · Sea view · Sauna", home_1_price: "from 4.800 kr / week", home_1_tag: "Most loved",
        home_2_name: "Skovly", home_2_meta: "Sleeps 6 · Wood stove · Fjord nearby", home_2_price: "from 4.200 kr / week", home_2_tag: "Quiet weeks",
        lifts_section_eyebrow: "Cranes & lifts",
        lifts_section_title: "When you need\nto reach higher.",
        lifts_section_body: "A small fleet of tracked spider lifts and a truck-mounted crane. Rented with or without an operator. Based in Ringkøbing.",
        lift_spider_name: "Spider lift 23m", lift_spider_meta: "Tracked · Indoor-safe · 230V",
        lift_truck_name: "Truck crane 30m", lift_truck_meta: "Road-legal · Operator included",
        lift_scissor_name: "Scissor 12m", lift_scissor_meta: "Electric · Narrow access",
        lift_cta: "Check availability",
        about_eyebrow: "The family",
        about_title: "Kirsten & Jens,\nand the two kids who grew up here.",
        about_body: "Jens bought his first crane in 1987 to help neighbours put up barns. The summer houses came later — one for the family, one we rented out, then we built a second. Kirsten still answers every email.",
        contact_title: "Get in touch",
        contact_body: "We usually reply the same day. Danish, English and German are all fine.",
        contact_phone: "+45 97 00 00 00", contact_email: "hej@pilegaard.dk",
        contact_address: "Klitvej 14 · 6950 Ringkøbing · Danmark",
        map_title: "Where to find us",
        map_body: "Both houses sit within 20 minutes of the farm. The cranes travel.",
        booking_title: "Book directly", booking_arrive: "Arrive", booking_depart: "Depart", booking_guests: "Guests",
        booking_check: "Check availability",
        booking_note: "No booking fee. Pay 30% now, the rest 30 days before arrival.",
        footer_small: "Pilegaard Udlejning ApS · CVR 12 34 56 78",
        footer_built: "Made with care in Ringkøbing",
        detail_back: "Back to all homes", detail_amenities: "What's here",
        detail_location: "Location", detail_rates: "Rates",
        detail_book: "Request these dates", detail_gallery: "Gallery", detail_story: "About the house",
        lift_detail_back: "Back to home", lift_request: "Request a quote",
    },
    da: {
        nav_homes: "Sommerhuse", nav_lifts: "Kraner & lifte", nav_about: "Familien", nav_contact: "Kontakt", nav_map: "Find vej",
        hero_eyebrow: "Lille familievirksomhed · Siden 1987",
        hero_title_a: "To sommerhuse\nved Vesterhavet.",
        hero_sub_a: "Drevet af familien Pilegaard fra en lille gård i Vestjylland. Lej et hus direkte, eller lån en kran når du skal bruge den.",
        hero_cta_primary: "Se husene", hero_cta_secondary: "Kraner & lifte",
        homes_section_eyebrow: "Sommerhuse",
        homes_section_title: "To huse,\nvalgt med omhu.",
        homes_section_body: "Vi lejer vores egne to huse ud — ingen bureau, intet gebyr. Det ene ligger i klitterne, det andet gemt i fyrretræerne. Begge har plads til seks.",
        home_1_name: "Havblik", home_1_meta: "Plads til 6 · Havudsigt · Sauna", home_1_price: "fra 4.800 kr / uge", home_1_tag: "Mest elsket",
        home_2_name: "Skovly", home_2_meta: "Plads til 6 · Brændeovn · Fjord tæt på", home_2_price: "fra 4.200 kr / uge", home_2_tag: "Stille uger",
        lifts_section_eyebrow: "Kraner & lifte",
        lifts_section_title: "Når du skal\nlidt højere op.",
        lifts_section_body: "Et lille udvalg af bæltelifte og en lastbilmonteret kran. Lejes med eller uden fører. Base i Ringkøbing.",
        lift_spider_name: "Edderkoppelift 23m", lift_spider_meta: "Bælter · Indendørs · 230V",
        lift_truck_name: "Lastbilkran 30m", lift_truck_meta: "Vejlovlig · Fører med",
        lift_scissor_name: "Sakselift 12m", lift_scissor_meta: "El-drift · Smal passage",
        lift_cta: "Se ledighed",
        about_eyebrow: "Familien",
        about_title: "Kirsten & Jens,\nog de to børn der voksede op her.",
        about_body: "Jens købte sin første kran i 1987 for at hjælpe naboerne med at rejse lader. Sommerhusene kom senere — ét til familien, ét vi lejede ud, og så byggede vi endnu et. Kirsten svarer stadig på hver mail.",
        contact_title: "Kom i kontakt",
        contact_body: "Vi svarer som regel samme dag. Dansk, engelsk og tysk går begge veje.",
        contact_phone: "+45 97 00 00 00", contact_email: "hej@pilegaard.dk",
        contact_address: "Klitvej 14 · 6950 Ringkøbing · Danmark",
        map_title: "Sådan finder du os",
        map_body: "Begge huse ligger inden for 20 minutter fra gården. Kranerne kører ud.",
        booking_title: "Book direkte", booking_arrive: "Ankomst", booking_depart: "Afrejse", booking_guests: "Gæster",
        booking_check: "Se ledighed",
        booking_note: "Ingen gebyr. Betal 30% nu, resten 30 dage før ankomst.",
        footer_small: "Pilegaard Udlejning ApS · CVR 12 34 56 78",
        footer_built: "Lavet med omhu i Ringkøbing",
        detail_back: "Tilbage til husene", detail_amenities: "Hvad der er",
        detail_location: "Beliggenhed", detail_rates: "Priser",
        detail_book: "Anmod om disse dage", detail_gallery: "Galleri", detail_story: "Om huset",
        lift_detail_back: "Tilbage til forsiden", lift_request: "Få et tilbud",
    },
    de: {
        nav_homes: "Ferienhäuser", nav_lifts: "Krane & Hebebühnen", nav_about: "Die Familie", nav_contact: "Kontakt", nav_map: "Anfahrt",
        hero_eyebrow: "Kleiner Familienbetrieb · Seit 1987",
        hero_title_a: "Zwei Ferienhäuser\nan der dänischen See.",
        hero_sub_a: "Geführt von Familie Pilegaard von einem kleinen Hof in Westjütland. Miete direkt ein Haus oder einen Kran, wenn du ihn brauchst.",
        hero_cta_primary: "Häuser ansehen", hero_cta_secondary: "Krane & Hebebühnen",
        homes_section_eyebrow: "Ferienhäuser",
        homes_section_title: "Zwei Häuser,\nmit Bedacht gewählt.",
        homes_section_body: "Wir vermieten unsere eigenen zwei Häuser — kein Makler, keine Provision. Eines liegt in den Dünen, das andere versteckt zwischen Kiefern. Beide für sechs Personen.",
        home_1_name: "Havblik", home_1_meta: "6 Personen · Meerblick · Sauna", home_1_price: "ab 640 € / Woche", home_1_tag: "Am beliebtesten",
        home_2_name: "Skovly", home_2_meta: "6 Personen · Kaminofen · Fjord nah", home_2_price: "ab 560 € / Woche", home_2_tag: "Ruhige Wochen",
        lifts_section_eyebrow: "Krane & Hebebühnen",
        lifts_section_title: "Wenn es\nhöher hinaus soll.",
        lifts_section_body: "Eine kleine Flotte Raupenlifte und ein LKW-Kran. Mit oder ohne Bediener mietbar. Basis in Ringkøbing.",
        lift_spider_name: "Raupenlift 23m", lift_spider_meta: "Raupen · Innentauglich · 230V",
        lift_truck_name: "LKW-Kran 30m", lift_truck_meta: "Straßenzugelassen · Mit Fahrer",
        lift_scissor_name: "Scherenlift 12m", lift_scissor_meta: "Elektro · Schmaler Zugang",
        lift_cta: "Verfügbarkeit prüfen",
        about_eyebrow: "Die Familie",
        about_title: "Kirsten & Jens,\nund die zwei Kinder von hier.",
        about_body: "Jens kaufte 1987 seinen ersten Kran, um Nachbarn beim Scheunenbau zu helfen. Die Ferienhäuser kamen später — eins für die Familie, eins zum Vermieten, dann bauten wir noch eins. Kirsten beantwortet jede Mail selbst.",
        contact_title: "Kontakt aufnehmen",
        contact_body: "Wir antworten meist am selben Tag. Dänisch, Deutsch und Englisch sind alle willkommen.",
        contact_phone: "+45 97 00 00 00", contact_email: "hej@pilegaard.dk",
        contact_address: "Klitvej 14 · 6950 Ringkøbing · Dänemark",
        map_title: "So findest du uns",
        map_body: "Beide Häuser liegen 20 Minuten vom Hof. Die Krane kommen zu dir.",
        booking_title: "Direkt buchen", booking_arrive: "Ankunft", booking_depart: "Abreise", booking_guests: "Personen",
        booking_check: "Verfügbarkeit prüfen",
        booking_note: "Keine Buchungsgebühr. 30% jetzt, Rest 30 Tage vor Ankunft.",
        footer_small: "Pilegaard Udlejning ApS · CVR 12 34 56 78",
        footer_built: "Mit Sorgfalt in Ringkøbing",
        detail_back: "Zurück zu allen Häusern", detail_amenities: "Was da ist",
        detail_location: "Lage", detail_rates: "Preise",
        detail_book: "Termin anfragen", detail_gallery: "Galerie", detail_story: "Über das Haus",
        lift_detail_back: "Zurück zur Startseite", lift_request: "Angebot anfragen",
    },
};

window.PILEGAARD_APPLY_I18N = function(lang, root = document) {
    const dict = window.PILEGAARD_I18N[lang];
    if (!dict) return;
    root.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (dict[key] != null) {
            if (dict[key].includes('\n')) {
                el.innerHTML = dict[key].split('\n').map(s => `<span class="line">${s}</span>`).join('');
            } else {
                el.textContent = dict[key];
            }
        }
    });
    document.documentElement.lang = lang;
};
